// Demo data for GrowthOS - used when external services are unavailable

export const demoLeads = [
  {
    id: 'lead-1',
    name: 'Sarah Chen',
    email: 'sarah@techcorp.com',
    phone: '+1 (555) 123-4567',
    company: 'TechCorp',
    title: 'VP of Marketing',
    source: 'website',
    status: 'qualified',
    score: 85,
    value: 15000,
    tags: ['enterprise', 'hot-lead', 'saas'],
    website: 'techcorp.com',
    lastContactAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
  },
  {
    id: 'lead-2',
    name: 'Marcus Johnson',
    email: 'marcus@innovate.io',
    phone: '+1 (555) 234-5678',
    company: 'Innovate.io',
    title: 'CEO',
    source: 'referral',
    status: 'proposal',
    score: 92,
    value: 25000,
    tags: ['startup', 'high-value', 'referral'],
    website: 'innovate.io',
    lastContactAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7).toISOString(),
  },
  {
    id: 'lead-3',
    name: 'Emily Rodriguez',
    email: 'emily@blueridge.co',
    phone: '+1 (555) 345-6789',
    company: 'BlueRidge Co',
    title: 'Marketing Director',
    source: 'linkedin',
    status: 'contacted',
    score: 68,
    value: 8000,
    tags: ['ecommerce', 'warm'],
    website: 'blueridge.co',
    lastContactAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
  },
  {
    id: 'lead-4',
    name: 'David Kim',
    email: 'david@acmecorp.com',
    phone: '+1 (555) 456-7890',
    company: 'Acme Corp',
    title: 'CTO',
    source: 'cold',
    status: 'new',
    score: 45,
    value: 12000,
    tags: ['enterprise', 'cold'],
    website: 'acmecorp.com',
    lastContactAt: null,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },
  {
    id: 'lead-5',
    name: 'Lisa Thompson',
    email: 'lisa@greenleaf.com',
    phone: '+1 (555) 567-8901',
    company: 'GreenLeaf',
    title: 'Head of Growth',
    source: 'event',
    status: 'negotiation',
    score: 88,
    value: 35000,
    tags: ['high-value', 'negotiation', 'saas'],
    website: 'greenleaf.com',
    lastContactAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString(),
  },
  {
    id: 'lead-6',
    name: 'James Wright',
    email: 'james@startupxyz.io',
    phone: '+1 (555) 678-9012',
    company: 'StartupXYZ',
    title: 'Founder',
    source: 'website',
    status: 'won',
    score: 95,
    value: 20000,
    tags: ['startup', 'closed-won', 'retainer'],
    website: 'startupxyz.io',
    lastContactAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 14).toISOString(),
  },
  {
    id: 'lead-7',
    name: 'Aisha Patel',
    email: 'aisha@cloudnine.tech',
    phone: '+1 (555) 789-0123',
    company: 'CloudNine Tech',
    title: 'VP of Sales',
    source: 'referral',
    status: 'qualified',
    score: 78,
    value: 18000,
    tags: ['tech', 'qualified', 'referral'],
    website: 'cloudnine.tech',
    lastContactAt: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4).toISOString(),
  },
  {
    id: 'lead-8',
    name: 'Robert Chang',
    email: 'robert@megacorp.com',
    phone: '+1 (555) 890-1234',
    company: 'MegaCorp',
    title: 'Director of Digital',
    source: 'linkedin',
    status: 'lost',
    score: 30,
    value: 50000,
    tags: ['enterprise', 'lost', 'budget'],
    website: 'megacorp.com',
    lastContactAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 20).toISOString(),
  },
]

export const demoAudits = [
  {
    id: 'audit-1',
    url: 'acmecorp.com',
    status: 'completed',
    progress: 100,
    overallScore: 62,
    seoScore: 58,
    uxScore: 71,
    performance: 55,
    accessibility: 64,
    findings: [
      { category: 'SEO', severity: 'high', title: 'Missing meta descriptions', description: '14 pages are missing meta description tags, impacting search engine click-through rates.' },
      { category: 'SEO', severity: 'medium', title: 'No structured data markup', description: 'No Schema.org markup found. Adding structured data can improve search visibility.' },
      { category: 'Performance', severity: 'high', title: 'Large uncompressed images', description: 'Found 8 images over 500KB. Implement WebP format and lazy loading.' },
      { category: 'UX', severity: 'medium', title: 'No clear CTA hierarchy', description: 'Multiple competing CTAs on homepage. Consider primary/secondary CTA structure.' },
      { category: 'Accessibility', severity: 'high', title: 'Low contrast ratio', description: '3 text elements fail WCAG AA contrast requirements.' },
      { category: 'Performance', severity: 'medium', title: 'Render-blocking JavaScript', description: '4 render-blocking JS files detected. Defer non-critical scripts.' },
    ],
    suggestions: [
      'Implement meta descriptions on all pages to improve SERP click-through rates by up to 30%',
      'Add Schema.org structured data for better rich snippet visibility',
      'Convert images to WebP and implement lazy loading to reduce page load by 40%',
      'Redesign CTA hierarchy with one primary action per page section',
      'Fix color contrast issues to meet WCAG AA standards',
      'Defer non-critical JavaScript to improve First Contentful Paint',
    ],
    completedAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
  },
  {
    id: 'audit-2',
    url: 'techcorp.com',
    status: 'completed',
    progress: 100,
    overallScore: 78,
    seoScore: 82,
    uxScore: 74,
    performance: 79,
    accessibility: 77,
    findings: [
      { category: 'SEO', severity: 'low', title: 'H1 tag duplication', description: '2 pages have multiple H1 tags which can confuse search engines.' },
      { category: 'UX', severity: 'medium', title: 'Mobile navigation issues', description: 'Hamburger menu closes unexpectedly on scroll.' },
      { category: 'Performance', severity: 'low', title: 'Unused CSS rules', description: 'Approximately 35% of CSS rules are unused on the homepage.' },
    ],
    suggestions: [
      'Fix H1 tag structure to have exactly one H1 per page',
      'Fix mobile navigation scroll behavior',
      'Purge unused CSS to reduce stylesheet size',
    ],
    completedAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
  },
  {
    id: 'audit-3',
    url: 'innovate.io',
    status: 'running',
    progress: 65,
    overallScore: null,
    seoScore: null,
    uxScore: null,
    performance: null,
    accessibility: null,
    findings: [],
    suggestions: [],
    completedAt: null,
    createdAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
  },
]

export const demoOutreach = [
  {
    id: 'outreach-1',
    name: 'SaaS Decision Makers Campaign',
    type: 'cold_email',
    tone: 'professional',
    industry: 'SaaS',
    targetAudience: 'CTOs and VP of Engineering at mid-market SaaS companies',
    subjectLine: 'Grow your MRR by 40% — proven framework inside',
    content: `Hi {{firstName}},\n\nI noticed {{company}} is scaling fast — congrats on the recent growth.\n\nI'm reaching out because we've helped 50+ SaaS companies similar to {{company}} accelerate their MRR growth by an average of 40% in 6 months.\n\nOur framework focuses on three pillars:\n1. Conversion-optimized landing pages\n2. Data-driven email sequences\n3. Automated lead scoring & nurturing\n\nWould you be open to a 15-minute call this week to see if this could work for {{company}}?\n\nBest,\nAlex`,
    cta: 'Book a 15-min discovery call',
    sequence: [
      { step: 1, type: 'email', delay: '0 days', subject: 'Grow your MRR by 40% — proven framework inside' },
      { step: 2, type: 'email', delay: '3 days', subject: 'Re: {{company}} growth framework' },
      { step: 3, type: 'linkedin', delay: '7 days', subject: 'Connection request + message' },
      { step: 4, type: 'email', delay: '10 days', subject: 'Quick question about {{company}} growth goals' },
    ],
    status: 'active',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
  },
  {
    id: 'outreach-2',
    name: 'E-commerce Follow-up Sequence',
    type: 'follow_up',
    tone: 'friendly',
    industry: 'E-commerce',
    targetAudience: 'Marketing directors at e-commerce brands',
    subjectLine: 'Your website audit results are ready',
    content: `Hi {{firstName}},\n\nThanks for requesting a website audit for {{company}}. We've completed the analysis and found some exciting opportunities.\n\nKey findings:\n• Your site could load 40% faster\n• 3 conversion blockers we identified\n• SEO opportunities worth an estimated 2,000+ monthly visitors\n\nWould you like me to walk you through the results?\n\nCheers,\nAlex`,
    cta: 'Schedule audit review call',
    sequence: [
      { step: 1, type: 'email', delay: '0 days', subject: 'Your website audit results are ready' },
      { step: 2, type: 'email', delay: '2 days', subject: 'Quick recap of {{company}} audit findings' },
      { step: 3, type: 'email', delay: '5 days', subject: 'Still interested in those audit results?' },
    ],
    status: 'draft',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },
]

export const demoProposals = [
  {
    id: 'proposal-1',
    title: 'Digital Growth Strategy',
    clientName: 'StartupXYZ',
    clientEmail: 'james@startupxyz.io',
    status: 'accepted',
    sections: [
      { title: 'Executive Summary', content: 'We propose a comprehensive digital growth strategy for StartupXYZ that focuses on scalable customer acquisition and conversion optimization.' },
      { title: 'Current State Analysis', content: 'Based on our audit, StartupXYZ has a strong product but underperforming marketing funnel with a 1.2% conversion rate.' },
      { title: 'Proposed Strategy', content: 'Our 3-phase approach includes: (1) Funnel optimization, (2) Content marketing engine, (3) Paid acquisition scaling.' },
      { title: 'Timeline & Milestones', content: 'Phase 1: Weeks 1-4 | Phase 2: Weeks 5-12 | Phase 3: Weeks 13-24' },
    ],
    pricing: [
      { item: 'Funnel Optimization', description: 'Landing pages, CRO, A/B testing', quantity: 1, price: 5000 },
      { item: 'Content Marketing', description: 'Blog, case studies, whitepapers', quantity: 3, price: 2000 },
      { item: 'Paid Media Management', description: 'Google Ads, LinkedIn Ads', quantity: 6, price: 1500 },
      { item: 'Monthly Retainer', description: 'Ongoing optimization & reporting', quantity: 6, price: 2000 },
    ],
    totalValue: 35000,
    shareToken: 'share-abc123',
    sentAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
    viewedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
    acceptedAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
  },
  {
    id: 'proposal-2',
    title: 'SEO & Content Overhaul',
    clientName: 'TechCorp',
    clientEmail: 'sarah@techcorp.com',
    status: 'sent',
    sections: [
      { title: 'Executive Summary', content: 'A targeted SEO and content overhaul to position TechCorp as the industry thought leader and capture organic search traffic.' },
      { title: 'SEO Audit Findings', content: '58/100 SEO score. Key issues: missing meta descriptions, no structured data, poor internal linking.' },
      { title: 'Content Strategy', content: 'Create a content hub with pillar pages, cluster content, and distribution strategy targeting decision-makers.' },
    ],
    pricing: [
      { item: 'Technical SEO Fix', description: 'Site structure, schema, speed', quantity: 1, price: 4000 },
      { item: 'Content Creation', description: '8 pillar pages + 24 cluster articles', quantity: 1, price: 8000 },
      { item: 'Link Building', description: 'Outreach & guest posting campaign', quantity: 3, price: 1500 },
    ],
    totalValue: 16500,
    shareToken: 'share-def456',
    sentAt: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
    viewedAt: null,
    acceptedAt: null,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
  },
  {
    id: 'proposal-3',
    title: 'Full-Stack Marketing Retainer',
    clientName: 'GreenLeaf',
    clientEmail: 'lisa@greenleaf.com',
    status: 'draft',
    sections: [
      { title: 'Executive Summary', content: 'Comprehensive marketing retainer covering all digital channels for sustained growth.' },
    ],
    pricing: [
      { item: 'Monthly Retainer', description: 'Full marketing suite', quantity: 12, price: 5000 },
    ],
    totalValue: 60000,
    shareToken: null,
    sentAt: null,
    viewedAt: null,
    acceptedAt: null,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
  },
]

export const demoActivities = [
  { id: 'act-1', type: 'lead_created', title: 'New lead captured', description: 'David Kim from Acme Corp submitted a contact form', createdAt: new Date(Date.now() - 1000 * 60 * 5).toISOString() },
  { id: 'act-2', type: 'audit_completed', title: 'Website audit completed', description: 'Audit for acmecorp.com finished with score 62/100', createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString() },
  { id: 'act-3', type: 'proposal_accepted', title: 'Proposal accepted', description: 'StartupXYZ accepted the Digital Growth Strategy proposal ($35,000)', createdAt: new Date(Date.now() - 1000 * 60 * 60).toISOString() },
  { id: 'act-4', type: 'outreach_sent', title: 'Outreach campaign sent', description: 'SaaS Decision Makers campaign sent to 150 contacts', createdAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString() },
  { id: 'act-5', type: 'lead_status_change', title: 'Lead moved to negotiation', description: 'Lisa Thompson (GreenLeaf) moved to negotiation stage', createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString() },
  { id: 'act-6', type: 'audit_started', title: 'New audit started', description: 'Audit started for innovate.io', createdAt: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString() },
  { id: 'act-7', type: 'proposal_sent', title: 'Proposal sent', description: 'SEO & Content Overhaul proposal sent to TechCorp ($16,500)', createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString() },
  { id: 'act-8', type: 'lead_created', title: 'New referral lead', description: 'Aisha Patel from CloudNine Tech referred by Marcus Johnson', createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString() },
]

export const demoRevenueData = [
  { month: 'Jan', revenue: 12000, leads: 24, conversions: 3 },
  { month: 'Feb', revenue: 15000, leads: 31, conversions: 4 },
  { month: 'Mar', revenue: 18000, leads: 28, conversions: 5 },
  { month: 'Apr', revenue: 22000, leads: 35, conversions: 6 },
  { month: 'May', revenue: 28000, leads: 42, conversions: 8 },
  { month: 'Jun', revenue: 32000, leads: 48, conversions: 10 },
  { month: 'Jul', revenue: 35000, leads: 52, conversions: 11 },
  { month: 'Aug', revenue: 38000, leads: 55, conversions: 12 },
  { month: 'Sep', revenue: 42000, leads: 60, conversions: 14 },
  { month: 'Oct', revenue: 48000, leads: 65, conversions: 16 },
  { month: 'Nov', revenue: 52000, leads: 70, conversions: 18 },
  { month: 'Dec', revenue: 58000, leads: 78, conversions: 21 },
]

export const demoLeadSourceData = [
  { name: 'Website', value: 35, color: 'var(--chart-1)' },
  { name: 'Referral', value: 25, color: 'var(--chart-2)' },
  { name: 'LinkedIn', value: 20, color: 'var(--chart-3)' },
  { name: 'Cold Outreach', value: 12, color: 'var(--chart-4)' },
  { name: 'Events', value: 8, color: 'var(--chart-5)' },
]

export const demoPipelineData = [
  { stage: 'New', count: 12, value: 84000 },
  { stage: 'Contacted', count: 8, value: 64000 },
  { stage: 'Qualified', count: 6, value: 98000 },
  { stage: 'Proposal', count: 4, value: 82000 },
  { stage: 'Negotiation', count: 3, value: 85000 },
  { stage: 'Won', count: 5, value: 115000 },
]

export const demoTeamMembers = [
  { id: 'tm-1', name: 'Alex Morgan', role: 'Agency Owner', email: 'alex@growthagency.io', avatar: null, leads: 28, revenue: 142000, conversionRate: 18 },
  { id: 'tm-2', name: 'Jordan Lee', role: 'Sales Lead', email: 'jordan@growthagency.io', avatar: null, leads: 22, revenue: 98000, conversionRate: 15 },
  { id: 'tm-3', name: 'Casey Rivera', role: 'Account Manager', email: 'casey@growthagency.io', avatar: null, leads: 18, revenue: 76000, conversionRate: 12 },
]

export const demoPlans = [
  {
    id: 'free',
    name: 'Free',
    price: 0,
    interval: 'month',
    description: 'Get started with basic lead management',
    features: ['Up to 50 leads', 'Basic CRM', '1 website audit/month', 'Email support', 'Basic reporting'],
    limitations: ['No AI outreach', 'No proposals', 'No team members', 'Limited exports'],
    cta: 'Current Plan',
    popular: false,
  },
  {
    id: 'starter',
    name: 'Starter',
    price: 49,
    interval: 'month',
    description: 'For growing agencies and freelancers',
    features: ['Up to 500 leads', 'Full CRM with pipeline', '10 website audits/month', 'AI outreach generator', 'Proposal builder', 'Priority support', 'Custom reporting'],
    limitations: ['Up to 2 team members', 'Limited AI credits'],
    cta: 'Upgrade to Starter',
    popular: false,
  },
  {
    id: 'pro',
    name: 'Pro',
    price: 129,
    interval: 'month',
    description: 'For scaling agencies with teams',
    features: ['Unlimited leads', 'Full CRM with pipeline', 'Unlimited website audits', 'AI outreach with sequences', 'Advanced proposals + e-sign', 'Team collaboration (5 members)', 'API access', 'White-label reports', 'Dedicated account manager'],
    limitations: [],
    cta: 'Upgrade to Pro',
    popular: true,
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    price: 349,
    interval: 'month',
    description: 'For large agencies and organizations',
    features: ['Everything in Pro', 'Unlimited team members', 'Custom AI model training', 'Advanced analytics & BI', 'SSO & advanced security', 'Custom integrations', 'SLA guarantee', 'Onboarding & training', 'Custom contracts & invoicing'],
    limitations: [],
    cta: 'Contact Sales',
    popular: false,
  },
]

export const demoAdminStats = {
  totalUsers: 1247,
  activeUsers: 892,
  totalRevenue: 284500,
  monthlyRecurring: 47200,
  churnRate: 2.3,
  avgRevenuePerUser: 318,
  aiCreditsUsed: 15680,
  aiCreditsLimit: 25000,
  auditsThisMonth: 342,
  proposalsThisMonth: 156,
}

export const demoRecentUsers = [
  { id: 'ru-1', name: 'Alex Morgan', email: 'alex@growthagency.io', plan: 'Pro', status: 'active', joinedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30).toISOString() },
  { id: 'ru-2', name: 'Sam Taylor', email: 'sam@digitalboost.co', plan: 'Starter', status: 'active', joinedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 14).toISOString() },
  { id: 'ru-3', name: 'Priya Sharma', email: 'priya@growthlab.in', plan: 'Enterprise', status: 'active', joinedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7).toISOString() },
  { id: 'ru-4', name: 'Mike O\'Brien', email: 'mike@scaleworks.io', plan: 'Free', status: 'trialing', joinedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString() },
  { id: 'ru-5', name: 'Yuki Tanaka', email: 'yuki@zenmarketing.jp', plan: 'Pro', status: 'active', joinedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString() },
]
